name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Build the App
      run: npm run build
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './build'
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
